version: "3.9"

services:
  mt5:
    build:
      dockerfile: Dockerfile
    container_name: mt5
    volumes:
      - ./config:/config
    ports:
      - "3000:3000"   # KasmVNC web client
      - "5001:5001"   # MT5 API (optional)
    restart: unless-stopped
    env_file:
      - .env
